export const hexedMeadowCards = {
  hm101: {
    name: 'Beesty Boyz',
    armyCardID: 'hm101',
    move: 2,
    figures: 3,
    hexes: 1,
    race: 'bee',
    life: 1,
    range: 1,
    attack: 1,
    defense: 1,
    points: 20,
  },
  hm102: {
    name: 'B-squad',
    armyCardID: 'hm102',
    move: 2,
    figures: 2,
    hexes: 1,
    race: 'bee',
    life: 1,
    range: 1,
    attack: 2,
    defense: 2,
    points: 40,
  },
  hm103: {
    name: 'Queen Bae',
    armyCardID: 'hm103',
    move: 1,
    figures: 1,
    hexes: 2,
    race: 'bee',
    life: 3,
    range: 3,
    attack: 3,
    defense: 3,
    points: 100,
  },
  hm201: {
    name: 'ButterFries',
    armyCardID: 'hm201',
    move: 1,
    figures: 3,
    hexes: 1,
    race: 'butterfly',
    life: 1,
    range: 1,
    attack: 1,
    defense: 1,
    points: 20,
  },
  hm202: {
    name: 'Scarwings',
    armyCardID: 'hm202',
    move: 1,
    figures: 2,
    hexes: 1,
    race: 'butterfly',
    life: 1,
    range: 1,
    attack: 2,
    defense: 1,
    points: 20,
  },
  hm203: {
    name: 'Monarch',
    armyCardID: 'hm203',
    move: 2,
    figures: 1,
    hexes: 2,
    race: 'butterfly',
    life: 3,
    range: 3,
    attack: 3,
    defense: 3,
    points: 20,
  },
}
